"""Suivi des travaux d'ingestion : un état par vidéo, repris après interruption.

Le worker doit pouvoir tourner des heures, être arrêté, et reprendre sans
retraiter ce qui est déjà fait. C'est cette table qui le permet.

Elle crée son propre schéma, sur SQLite comme sur PostgreSQL, pour que le
worker fonctionne en développement local avant que PostgreSQL soit prêt.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from enum import StrEnum
from typing import Any

from database.driver import Driver

LOGGER = logging.getLogger(__name__)


class JobState(StrEnum):
    """Étapes du traitement d'une vidéo, dans l'ordre."""

    PENDING = "pending"
    DOWNLOADING = "downloading"
    DOWNLOADED = "downloaded"
    EXTRACTING_AUDIO = "extracting_audio"
    TRANSCRIBING = "transcribing"
    GENERATING_METADATA = "generating_metadata"
    CHUNKING = "chunking"
    EMBEDDING = "embedding"
    INDEXING = "indexing"
    COMPLETED = "completed"
    FAILED = "failed"


# États depuis lesquels on peut reprendre : ni terminé, ni définitivement en
# échec. Un état intermédiaire signifie que le worker s'est arrêté en route.
RESUMABLE = frozenset(JobState) - {JobState.COMPLETED, JobState.FAILED}

TERMINAL = frozenset({JobState.COMPLETED, JobState.FAILED})


@dataclass(slots=True)
class Job:
    file_id: str
    state: JobState
    step: str = ""
    retry_count: int = 0
    error_message: str = ""
    started_at: str = ""
    completed_at: str = ""

    @classmethod
    def from_row(cls, row: Any) -> "Job":
        return cls(
            file_id=row["file_id"],
            state=JobState(row["state"]),
            step=row["step"] or "",
            retry_count=int(row["retry_count"] or 0),
            error_message=row["error_message"] or "",
            started_at=row["started_at"] or "",
            completed_at=row["completed_at"] or "",
        )


DDL_SQLITE = """
CREATE TABLE IF NOT EXISTS ingestion_jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id TEXT NOT NULL UNIQUE,
    state TEXT NOT NULL DEFAULT 'pending',
    step TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    started_at TEXT,
    completed_at TEXT,
    updated_at TEXT
)
"""

DDL_POSTGRES = """
CREATE TABLE IF NOT EXISTS ingestion_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL UNIQUE,
    state TEXT NOT NULL DEFAULT 'pending',
    step TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    started_at TEXT,
    completed_at TEXT,
    updated_at TEXT
)
"""


class JobQueue:
    """File de travaux, adossée à la base."""

    def __init__(self, driver: Driver, max_retries: int = 3) -> None:
        self.driver = driver
        self.max_retries = max_retries
        self._ensure_table()

    def _ensure_table(self) -> None:
        ddl = DDL_SQLITE if self.driver.dialect == "sqlite" else DDL_POSTGRES
        with self.driver.connect() as conn:
            conn.execute(ddl)
            conn.execute("CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_state ON ingestion_jobs(state)")

    # ── Alimentation ────────────────────────────────────────────────────────

    def enqueue(self, file_ids: list[str]) -> int:
        """Ajoute des vidéos à traiter. Celles déjà connues sont ignorées :
        c'est ce qui rend le script d'alimentation rejouable."""
        if not file_ids:
            return 0
        added = 0
        with self.driver.connect() as conn:
            sql = self.driver.insert_or_ignore(
                "ingestion_jobs", ["file_id", "state", "updated_at"]
            ).replace("?, ?, ?", f"?, ?, {self.driver.now_sql}")
            for fid in file_ids:
                cur = conn.execute(sql, (fid, JobState.PENDING))
                added += getattr(cur, "rowcount", 0) or 0
        return max(added, 0)

    # ── Consommation ────────────────────────────────────────────────────────

    def claim_next(self) -> Job | None:
        """Prend le prochain travail à faire.

        Les travaux repris — arrêtés en cours d'étape — passent avant les
        nouveaux : mieux vaut finir ce qui est commencé que d'accumuler des
        traitements à moitié faits.
        """
        states = [s.value for s in RESUMABLE if s != JobState.PENDING]
        placeholders = ", ".join("?" for _ in states)
        with self.driver.connect() as conn:
            row = conn.execute(
                f"SELECT * FROM ingestion_jobs WHERE state IN ({placeholders}) "
                f"AND retry_count < ? ORDER BY id LIMIT 1",
                (*states, self.max_retries),
            ).fetchone()
            if row is None:
                row = conn.execute(
                    "SELECT * FROM ingestion_jobs WHERE state = ? ORDER BY id LIMIT 1",
                    (JobState.PENDING.value,),
                ).fetchone()
            return Job.from_row(row) if row else None

    def advance(self, file_id: str, state: JobState, step: str = "") -> None:
        with self.driver.connect() as conn:
            conn.execute(
                f"UPDATE ingestion_jobs SET state = ?, step = ?, updated_at = {self.driver.now_sql}, "
                f"started_at = COALESCE(started_at, {self.driver.now_sql}) WHERE file_id = ?",
                (state.value, step, file_id),
            )

    def complete(self, file_id: str) -> None:
        with self.driver.connect() as conn:
            conn.execute(
                f"UPDATE ingestion_jobs SET state = ?, step = '', error_message = '', "
                f"completed_at = {self.driver.now_sql}, updated_at = {self.driver.now_sql} "
                f"WHERE file_id = ?",
                (JobState.COMPLETED.value, file_id),
            )

    def fail(self, file_id: str, message: str) -> Job | None:
        """Compte l'échec. Au-delà du plafond de reprises, le travail s'arrête.

        Une panne passagère ne doit pas arrêter la chaîne ; une panne durable
        ne doit pas la faire tourner en rond.
        """
        with self.driver.connect() as conn:
            conn.execute(
                "UPDATE ingestion_jobs SET retry_count = retry_count + 1, error_message = ? "
                f"WHERE file_id = ?",
                (message[:2000], file_id),
            )
            row = conn.execute(
                "SELECT * FROM ingestion_jobs WHERE file_id = ?", (file_id,)
            ).fetchone()
            if row and int(row["retry_count"] or 0) >= self.max_retries:
                conn.execute(
                    f"UPDATE ingestion_jobs SET state = ?, completed_at = {self.driver.now_sql} "
                    f"WHERE file_id = ?",
                    (JobState.FAILED.value, file_id),
                )
                row = conn.execute(
                    "SELECT * FROM ingestion_jobs WHERE file_id = ?", (file_id,)
                ).fetchone()
        return Job.from_row(row) if row else None

    def reset(self, file_id: str) -> None:
        """Remet un travail à zéro. C'est le « sauf si explicitement demandé »
        de la règle d'idempotence."""
        with self.driver.connect() as conn:
            conn.execute(
                "UPDATE ingestion_jobs SET state = ?, step = '', retry_count = 0, "
                "error_message = '', started_at = NULL, completed_at = NULL WHERE file_id = ?",
                (JobState.PENDING.value, file_id),
            )

    # ── Observabilité ───────────────────────────────────────────────────────

    def counts(self) -> dict[str, int]:
        with self.driver.connect() as conn:
            rows = conn.execute(
                "SELECT state, COUNT(*) FROM ingestion_jobs GROUP BY state"
            ).fetchall()
        return {r[0]: r[1] for r in rows}

    def get(self, file_id: str) -> Job | None:
        with self.driver.connect() as conn:
            row = conn.execute(
                "SELECT * FROM ingestion_jobs WHERE file_id = ?", (file_id,)
            ).fetchone()
        return Job.from_row(row) if row else None
