"""Persistance de la base de connaissance : transcriptions, fragments, vecteurs.

Ce module possède le schéma des tables de connaissance pour **les deux
moteurs**, et `schema_pg` le lui emprunte : une seule source, donc rien qui
puisse diverger.

Le stockage des vecteurs est le seul endroit où les deux moteurs s'éloignent
vraiment. PostgreSQL a `pgvector` et son type `vector(n)`. SQLite n'a rien
d'équivalent : on y range les vecteurs en BLOB et la similarité se calcule en
NumPy. À l'échelle du corpus — de l'ordre de 25 000 fragments, soit 38 Mo de
vecteurs — un parcours exhaustif prend moins de dix millisecondes, donc cette
solution de repli n'est pas une dégradation.
"""

from __future__ import annotations

import json
import logging
import struct
from dataclasses import dataclass
from typing import Any, Iterable, Sequence

from database.driver import Connection, Driver
from knowledge.chunking import Chunk, Segment

LOGGER = logging.getLogger(__name__)


# ── Schéma ──────────────────────────────────────────────────────────────────

def knowledge_ddl(dialect: str, vector_dim: int = 384) -> list[str]:
    """DDL des tables de connaissance, pour SQLite ou PostgreSQL."""
    pg = dialect == "postgresql"
    ident = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if pg else "INTEGER PRIMARY KEY AUTOINCREMENT"
    reel = "DOUBLE PRECISION" if pg else "REAL"
    jsonb = "JSONB" if pg else "TEXT"
    vecteur = f"vector({vector_dim})" if pg else "BLOB"

    ddl = [
        f"""
        CREATE TABLE IF NOT EXISTS knowledge_sources (
            id {ident},
            source_uid TEXT NOT NULL UNIQUE,
            source_type TEXT NOT NULL,
            title TEXT,
            speaker TEXT,
            source_url TEXT,
            language TEXT,
            metadata {jsonb},
            created_at TEXT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS transcripts (
            id {ident},
            source_uid TEXT NOT NULL UNIQUE,
            model TEXT,
            languages TEXT,
            duration_seconds {reel},
            segment_count INTEGER,
            created_at TEXT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS transcript_segments (
            id {ident},
            source_uid TEXT NOT NULL,
            segment_index INTEGER NOT NULL,
            start_time {reel} NOT NULL,
            end_time {reel} NOT NULL,
            text TEXT NOT NULL,
            language TEXT,
            speaker_role TEXT,
            speaker_label TEXT,
            confidence {reel},
            UNIQUE (source_uid, segment_index)
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS chunks (
            id {ident},
            chunk_uid TEXT NOT NULL UNIQUE,
            source_uid TEXT NOT NULL,
            source_type TEXT NOT NULL DEFAULT 'video',
            text TEXT NOT NULL,
            language TEXT,
            speaker_role TEXT,
            start_time {reel},
            end_time {reel},
            page INTEGER,
            chapter TEXT,
            verse TEXT,
            document_title TEXT,
            speaker TEXT,
            source_url TEXT,
            metadata {jsonb},
            created_at TEXT
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS chunk_embeddings (
            chunk_id BIGINT PRIMARY KEY,
            model TEXT NOT NULL,
            dim INTEGER NOT NULL,
            embedding {vecteur}
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_segments_source ON transcript_segments(source_uid)",
        "CREATE INDEX IF NOT EXISTS idx_segments_language ON transcript_segments(language)",
        "CREATE INDEX IF NOT EXISTS idx_chunks_source ON chunks(source_uid)",
        "CREATE INDEX IF NOT EXISTS idx_chunks_language ON chunks(language)",
        "CREATE INDEX IF NOT EXISTS idx_knowledge_sources_type ON knowledge_sources(source_type)",
    ]

    if pg:
        # Recherche lexicale sur les fragments, jumelle de celle des vidéos.
        ddl += [
            "ALTER TABLE chunks ADD COLUMN IF NOT EXISTS document tsvector",
            "CREATE INDEX IF NOT EXISTS idx_chunks_document ON chunks USING GIN (document)",
        ]
    else:
        ddl += [
            """
            CREATE VIRTUAL TABLE IF NOT EXISTS chunks_fts USING fts5(
                chunk_uid UNINDEXED, text, language UNINDEXED
            )
            """
        ]
    return ddl


# ── Vecteurs ────────────────────────────────────────────────────────────────

def pack_vector(values: Sequence[float]) -> bytes:
    """Encode un vecteur en float32, pour le stockage SQLite."""
    return struct.pack(f"<{len(values)}f", *values)


def unpack_vector(blob: bytes) -> list[float]:
    return list(struct.unpack(f"<{len(blob) // 4}f", blob))


@dataclass(slots=True)
class ChunkHit:
    """Un fragment retrouvé, avec de quoi le citer."""

    chunk_uid: str
    source_uid: str
    text: str
    score: float
    language: str = ""
    speaker_role: str = ""
    start_time: float | None = None
    end_time: float | None = None
    document_title: str = ""
    speaker: str = ""
    source_url: str = ""

    @classmethod
    def from_row(cls, row: Any, score: float) -> "ChunkHit":
        return cls(
            chunk_uid=row["chunk_uid"],
            source_uid=row["source_uid"],
            text=row["text"],
            score=score,
            language=row["language"] or "",
            speaker_role=row["speaker_role"] or "",
            start_time=row["start_time"],
            end_time=row["end_time"],
            document_title=row["document_title"] or "",
            speaker=row["speaker"] or "",
            source_url=row["source_url"] or "",
        )


class KnowledgeRepository:
    def __init__(self, driver: Driver, vector_dim: int = 384) -> None:
        self.driver = driver
        self.vector_dim = vector_dim
        self._ensure_tables()

    def _ensure_tables(self) -> None:
        with self.driver.connect() as conn:
            if self.driver.dialect == "postgresql":
                conn.execute("CREATE EXTENSION IF NOT EXISTS vector")
            for stmt in knowledge_ddl(self.driver.dialect, self.vector_dim):
                conn.execute(stmt)

    # ── Transcriptions ──────────────────────────────────────────────────────

    def save_transcript(
        self,
        source_uid: str,
        segments: Sequence[Segment],
        *,
        model: str,
        languages: Sequence[str],
        duration: float,
    ) -> int:
        """Enregistre une transcription et ses segments. Rejouable."""
        now = self.driver.now_sql
        with self.driver.connect() as conn:
            conn.execute("DELETE FROM transcript_segments WHERE source_uid = ?", (source_uid,))
            conn.execute("DELETE FROM transcripts WHERE source_uid = ?", (source_uid,))
            conn.execute(
                f"INSERT INTO transcripts(source_uid, model, languages, duration_seconds, "
                f"segment_count, created_at) VALUES(?, ?, ?, ?, ?, {now})",
                (source_uid, model, "; ".join(languages), float(duration), len(segments)),
            )
            conn.executemany(
                "INSERT INTO transcript_segments(source_uid, segment_index, start_time, "
                "end_time, text, language, speaker_role, speaker_label) "
                "VALUES(?, ?, ?, ?, ?, ?, ?, ?)",
                [
                    (source_uid, i, s.start, s.end, s.text, s.language,
                     s.speaker_role, s.speaker_label)
                    for i, s in enumerate(segments)
                ],
            )
        return len(segments)

    def get_segments(self, source_uid: str) -> list[Segment]:
        with self.driver.connect() as conn:
            rows = conn.execute(
                "SELECT * FROM transcript_segments WHERE source_uid = ? ORDER BY segment_index",
                (source_uid,),
            ).fetchall()
        return [
            Segment(
                start=float(r["start_time"]), end=float(r["end_time"]), text=r["text"],
                language=r["language"] or "", speaker_role=r["speaker_role"] or "unknown",
                speaker_label=r["speaker_label"] or "",
            )
            for r in rows
        ]

    def has_transcript(self, source_uid: str) -> bool:
        """Sert l'idempotence du worker : ne pas retranscrire ce qui l'est déjà."""
        with self.driver.connect() as conn:
            row = conn.execute(
                "SELECT 1 FROM transcripts WHERE source_uid = ?", (source_uid,)
            ).fetchone()
        return row is not None

    # ── Fragments ───────────────────────────────────────────────────────────

    def save_chunks(
        self,
        source_uid: str,
        chunks: Sequence[Chunk],
        *,
        source_type: str = "video",
        document_title: str = "",
        speaker: str = "",
        source_url: str = "",
    ) -> int:
        """Remplace les fragments d'une source. Les vecteurs suivent la cascade."""
        now = self.driver.now_sql
        with self.driver.connect() as conn:
            anciens = [
                r[0] for r in conn.execute(
                    "SELECT id FROM chunks WHERE source_uid = ?", (source_uid,)
                ).fetchall()
            ]
            if anciens:
                marques = ", ".join("?" for _ in anciens)
                conn.execute(f"DELETE FROM chunk_embeddings WHERE chunk_id IN ({marques})", tuple(anciens))
            conn.execute("DELETE FROM chunks WHERE source_uid = ?", (source_uid,))
            if self.driver.dialect == "sqlite":
                conn.execute("DELETE FROM chunks_fts WHERE chunk_uid LIKE ?", (f"{source_uid}#%",))

            for i, c in enumerate(chunks):
                uid = f"{source_uid}#{i:04d}"
                conn.execute(
                    f"INSERT INTO chunks(chunk_uid, source_uid, source_type, text, language, "
                    f"speaker_role, start_time, end_time, document_title, speaker, source_url, "
                    f"metadata, created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,{now})",
                    (uid, source_uid, source_type, c.text, c.language, c.speaker_role,
                     c.start_time, c.end_time, document_title, speaker, source_url,
                     json.dumps(c.metadata, ensure_ascii=False)),
                )
                if self.driver.dialect == "sqlite":
                    conn.execute(
                        "INSERT INTO chunks_fts(chunk_uid, text, language) VALUES(?,?,?)",
                        (uid, c.text, c.language),
                    )
            if self.driver.dialect == "postgresql" and chunks:
                # Le tsvector se calcule côté serveur, une fois pour toutes.
                conn.execute(
                    "UPDATE chunks SET document = to_tsvector('french', text) "
                    "WHERE source_uid = ? AND document IS NULL",
                    (source_uid,),
                )
        return len(chunks)

    def get_chunks(self, source_uid: str) -> list[dict[str, Any]]:
        with self.driver.connect() as conn:
            rows = conn.execute(
                "SELECT * FROM chunks WHERE source_uid = ? ORDER BY id", (source_uid,)
            ).fetchall()
        return [dict(r) for r in rows]

    def chunks_without_embeddings(self, limit: int = 500) -> list[dict[str, Any]]:
        with self.driver.connect() as conn:
            rows = conn.execute(
                "SELECT c.id, c.chunk_uid, c.text FROM chunks c "
                "LEFT JOIN chunk_embeddings e ON e.chunk_id = c.id "
                "WHERE e.chunk_id IS NULL ORDER BY c.id LIMIT ?",
                (limit,),
            ).fetchall()
        return [dict(r) for r in rows]

    # ── Vecteurs ────────────────────────────────────────────────────────────

    def save_embeddings(
        self, pairs: Iterable[tuple[int, Sequence[float]]], *, model: str
    ) -> int:
        """Range les vecteurs. PostgreSQL les typa, SQLite les met en BLOB."""
        pg = self.driver.dialect == "postgresql"
        n = 0
        with self.driver.connect() as conn:
            for chunk_id, vec in pairs:
                valeur = "[" + ",".join(f"{v:.6f}" for v in vec) + "]" if pg else pack_vector(vec)
                conn.execute("DELETE FROM chunk_embeddings WHERE chunk_id = ?", (chunk_id,))
                conn.execute(
                    "INSERT INTO chunk_embeddings(chunk_id, model, dim, embedding) VALUES(?,?,?,?)",
                    (chunk_id, model, len(vec), valeur),
                )
                n += 1
        return n

    # ── Comptes ─────────────────────────────────────────────────────────────

    def counts(self) -> dict[str, int]:
        """Les métriques que réclame l'observabilité."""
        out: dict[str, int] = {}
        with self.driver.connect() as conn:
            for table in ("knowledge_sources", "transcripts", "transcript_segments",
                          "chunks", "chunk_embeddings"):
                out[table] = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        return out
