"""Schéma PostgreSQL, dérivé du schéma SQLite par introspection.

`database/schema.py` reste la source de vérité et n'est pas touché : c'est lui
qui tourne en production. Plutôt que d'en recopier les 68 colonnes dans une
seconde liste — qui divergerait au premier ajout — on lit le schéma réel de la
base SQLite et on le traduit. Il n'y a donc rien à tenir à jour.

Deux choses ne se traduisent pas et sont écrites à la main :
  · l'index plein texte, FTS5 d'un côté, `tsvector` + GIN de l'autre ;
  · les tables de la base de connaissance, qui n'existent pas encore en SQLite.
"""

from __future__ import annotations

import logging
import sqlite3
from pathlib import Path
from typing import Any

from database.driver import Connection, Driver

LOGGER = logging.getLogger(__name__)

# Tables internes de FTS5 : elles n'ont pas d'équivalent et se recréent seules.
FTS_SHADOW = {
    "videos_fts",
    "videos_fts_config",
    "videos_fts_content",
    "videos_fts_data",
    "videos_fts_docsize",
    "videos_fts_idx",
}

# Colonnes indexées par l'ancien FTS5, reprises telles quelles dans le tsvector.
FTS_FIELDS = [
    "internal_video_id", "file_name", "clean_title", "editorial_title",
    "original_title", "alternate_titles", "folder_path", "speaker", "preacher",
    "ministry", "main_theme", "spiritual_themes", "doctrine_topics",
    "biblical_topics", "bible_references", "songs", "worship_leaders",
    "content_type", "event_name", "location", "series_name", "teaching_type",
    "ai_summary", "transcript_summary", "keywords", "semantic_tags",
]

TYPE_MAP = {
    "TEXT": "TEXT",
    "INTEGER": "BIGINT",
    "REAL": "DOUBLE PRECISION",
    "BLOB": "BYTEA",
    "NUMERIC": "NUMERIC",
    "": "TEXT",
}


def _pg_type(sqlite_type: str) -> str:
    base = (sqlite_type or "").upper().split("(")[0].strip()
    return TYPE_MAP.get(base, "TEXT")


def _read_sqlite_schema(db_path: Path) -> dict[str, dict[str, Any]]:
    """Relève tables, colonnes et index uniques de la base SQLite."""
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    schema: dict[str, dict[str, Any]] = {}
    try:
        tables = [
            r[0] for r in conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table' "
                "AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
        ]
        for table in tables:
            if table in FTS_SHADOW:
                continue
            cols = []
            for r in conn.execute(f'PRAGMA table_info("{table}")'):
                cols.append({
                    "name": r["name"],
                    "type": r["type"],
                    "notnull": bool(r["notnull"]),
                    "default": r["dflt_value"],
                    "pk": bool(r["pk"]),
                })
            uniques = []
            for idx in conn.execute(f'PRAGMA index_list("{table}")'):
                if not idx["unique"]:
                    continue
                members = [c["name"] for c in conn.execute(f'PRAGMA index_info("{idx["name"]}")')]
                if members:
                    uniques.append(members)
            schema[table] = {"columns": cols, "uniques": uniques}
    finally:
        conn.close()
    return schema


def _create_table_sql(table: str, spec: dict[str, Any]) -> str:
    parts: list[str] = []
    pks = [c["name"] for c in spec["columns"] if c["pk"]]
    for col in spec["columns"]:
        # Une clé primaire INTEGER de SQLite est un compteur automatique.
        if col["pk"] and _pg_type(col["type"]) == "BIGINT" and len(pks) == 1:
            parts.append(f'"{col["name"]}" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
            continue
        frag = f'"{col["name"]}" {_pg_type(col["type"])}'
        if col["notnull"]:
            frag += " NOT NULL"
        if col["default"] is not None:
            frag += f" DEFAULT {col['default']}"
        parts.append(frag)
    if len(pks) > 1 or (pks and _pg_type(next(c["type"] for c in spec["columns"] if c["pk"])) != "BIGINT"):
        parts.append(f'PRIMARY KEY ({", ".join(chr(34) + p + chr(34) for p in pks)})')
    for members in spec["uniques"]:
        parts.append(f'UNIQUE ({", ".join(chr(34) + m + chr(34) for m in members)})')
    body = ",\n    ".join(parts)
    return f'CREATE TABLE IF NOT EXISTS "{table}" (\n    {body}\n)'


def _fts_sql() -> list[str]:
    """Index plein texte PostgreSQL, équivalent de `videos_fts`.

    La configuration `french` apporte la racinisation et les mots vides, que le
    tokeniseur `unicode61` de FTS5 ne fait pas. La recherche y gagne.
    """
    return [
        """
        CREATE TABLE IF NOT EXISTS videos_fts (
            file_id TEXT PRIMARY KEY,
            document tsvector
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_videos_fts_document ON videos_fts USING GIN (document)",
    ]


def _knowledge_sql(vector_dim: int) -> list[str]:
    """Tables de la base de connaissance. Elles n'existent pas en SQLite."""
    return [
        """
        CREATE TABLE IF NOT EXISTS ingestion_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            file_id TEXT NOT NULL UNIQUE,
            state TEXT NOT NULL DEFAULT 'pending',
            step TEXT,
            retry_count INTEGER NOT NULL DEFAULT 0,
            error_message TEXT,
            started_at TEXT,
            completed_at TEXT,
            updated_at TEXT
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_state ON ingestion_jobs(state)",
        """
        CREATE TABLE IF NOT EXISTS knowledge_sources (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_uid TEXT NOT NULL UNIQUE,
            source_type TEXT NOT NULL,
            title TEXT,
            speaker TEXT,
            source_url TEXT,
            language TEXT,
            metadata JSONB,
            created_at TEXT
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_knowledge_sources_type ON knowledge_sources(source_type)",
        """
        CREATE TABLE IF NOT EXISTS transcripts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_uid TEXT NOT NULL UNIQUE,
            model TEXT,
            languages TEXT,
            duration_seconds DOUBLE PRECISION,
            segment_count INTEGER,
            created_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS transcript_segments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_uid TEXT NOT NULL,
            segment_index INTEGER NOT NULL,
            start_time DOUBLE PRECISION NOT NULL,
            end_time DOUBLE PRECISION NOT NULL,
            text TEXT NOT NULL,
            language TEXT,
            speaker_role TEXT,
            speaker_label TEXT,
            confidence DOUBLE PRECISION,
            UNIQUE (source_uid, segment_index)
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_segments_source ON transcript_segments(source_uid)",
        "CREATE INDEX IF NOT EXISTS idx_segments_language ON transcript_segments(language)",
        """
        CREATE TABLE IF NOT EXISTS chunks (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            chunk_uid TEXT NOT NULL UNIQUE,
            source_uid TEXT NOT NULL,
            source_type TEXT NOT NULL DEFAULT 'video',
            text TEXT NOT NULL,
            language TEXT,
            speaker_role TEXT,
            start_time DOUBLE PRECISION,
            end_time DOUBLE PRECISION,
            page INTEGER,
            chapter TEXT,
            verse TEXT,
            document_title TEXT,
            speaker TEXT,
            source_url TEXT,
            metadata JSONB,
            document tsvector,
            created_at TEXT
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_chunks_source ON chunks(source_uid)",
        "CREATE INDEX IF NOT EXISTS idx_chunks_language ON chunks(language)",
        "CREATE INDEX IF NOT EXISTS idx_chunks_document ON chunks USING GIN (document)",
        f"""
        CREATE TABLE IF NOT EXISTS chunk_embeddings (
            chunk_id BIGINT PRIMARY KEY REFERENCES chunks(id) ON DELETE CASCADE,
            model TEXT NOT NULL,
            dim INTEGER NOT NULL,
            embedding vector({vector_dim})
        )
        """,
    ]


def ensure_postgres_schema(
    driver: Driver,
    sqlite_path: Path | str,
    vector_dim: int = 384,
) -> dict[str, int]:
    """Crée le schéma dans PostgreSQL. Rejouable sans dommage."""
    if driver.dialect != "postgresql":
        raise ValueError("ensure_postgres_schema attend un pilote PostgreSQL")

    schema = _read_sqlite_schema(Path(sqlite_path))
    made = {"tables": 0, "index": 0}

    with driver.connect() as conn:
        conn.execute("CREATE EXTENSION IF NOT EXISTS vector")

        for table, spec in schema.items():
            conn.execute(_create_table_sql(table, spec))
            made["tables"] += 1

        for stmt in _fts_sql() + _knowledge_sql(vector_dim):
            conn.execute(stmt)
            if stmt.strip().upper().startswith("CREATE INDEX"):
                made["index"] += 1
            else:
                made["tables"] += 1

        _create_vector_index(conn, vector_dim)

    LOGGER.info("Schéma PostgreSQL prêt : %s", made)
    return made


def _create_vector_index(conn: Connection, vector_dim: int) -> None:
    """Index HNSW pour la recherche par similarité cosinus.

    Il n'est pas indispensable à cette échelle — 25 000 chunks se parcourent
    en quelques millisecondes — mais il ne coûte rien à créer maintenant et
    évite d'y revenir quand le corpus grandira.
    """
    try:
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_chunk_embeddings_hnsw "
            "ON chunk_embeddings USING hnsw (embedding vector_cosine_ops)"
        )
    except Exception as exc:  # pragma: no cover - dépend de la version pgvector
        LOGGER.warning("Index HNSW non créé (pgvector trop ancien ?) : %s", exc)
